Try to execute both 'gpg' and 'gpg2' as GPG binary.

diff --git a/init b/init
--- a/init
+++ b/init
@@ -5,12 +5,20 @@ if [[ -z "$1" || -z "$2" || -z "$3" || -z "$4" || -z "$5" ]]; then
     exit 1
 fi
 
+. scripts/functions
+
 hostname=${1}
 port=${2}
 email=${3}
 nokey=1
+gpg=$(findGPG)
 
-keyemails=$(gpg --list-keys 2> /dev/null | grep ^uid 2> /dev/null | perl -ne '/<(.*)>/ && print $1."\n"')
+if [ -z "$gpg" ]; then
+    echo "Could not find GPG executable on the \$PATH"
+    exit 1
+fi
+
+keyemails=$($gpg --list-keys 2> /dev/null | grep ^uid 2> /dev/null | perl -ne '/<(.*)>/ && print $1."\n"')
 
 if [[ -z "${keyemails}" ]]; then
     echo "No GPG keys. You need to create at least one."
@@ -41,7 +49,7 @@ echo "A gitgeist site" > config/title
 
 # Export the key we'll use for this repository.
 if [[ ! -f data/key.gpg ]]; then
-    gpg --armor --output data/key.gpg --export $3
+    $gpg --armor --output data/key.gpg --export $3
 fi
 
 # Initialize the local git repository for the content.
@@ -59,11 +67,13 @@ touch .git/git-daemon-export-ok
 cp scripts/data/style.css .
 cp scripts/data/logo.png .
 cp scripts/getkeyid .
+cp scripts/functions .
 
 git add posts
 git add following
 git add style.css
 git add getkeyid
+git add functions
 
 git commit -m "Initialisation commit."
 
